version: '3.4'

services:
  webapi: &conf
    image: ${DOCKER_REGISTRY-}webapi
    environment: &env
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

  webapi2:
    <<: *conf
    environment:
     - ASPNETCORE_URLS=http://+:81;
    ports:
     - "81"

  webapi3:
    <<: *conf
    environment:
     - ASPNETCORE_URLS=http://+:82;
    ports:
     - "82"

  nginx:
    depends_on:
     - webapi
     - webapi2
     - webapi3
    image: byjg/nginx-extras
    ports:
     - "80:80"
    volumes:
     - ./WebAPI/server/default.conf:/etc/nginx/conf.d/default.conf:ro
     - ./WebAPI/wwwroot:/home/static:ro

networks:
  default:
    name: mynet