version: '3.4'

services:
  webapi: &conf
    image: ${DOCKER_REGISTRY-}webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:440;
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
     - "440:440"
    volumes:
     - ./WebAPI/IsolatedStorage:/app/IsolatedStorage

  webapi2:
    <<: *conf
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:442;
    ports:
     - "442:442"
    volumes:
     - ./WebAPI/IsolatedStorage:/app/IsolatedStorage:ro

  webapi3:
    <<: *conf
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:441;
    ports:
     - "441:441"
    volumes:
     - ./WebAPI/IsolatedStorage:/app/IsolatedStorage:ro

  mirror:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: mirror
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:444;
    ports:
     - "444:444"
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

  nginx:
    depends_on:
     - webapi
     - webapi2
     - webapi3
     - mirror
    #image: byjg/nginx-extras
    image: macbre/nginx-http3:1.23.1
    ports:
      - "443:443/tcp"
      - "443:443/udp"
      - "80:80/tcp"
      - "80:80/udp"
    volumes:
     - ./WebAPI/server/nginx.conf:/etc/nginx/nginx.conf
     - ./WebAPI/wwwroot:/home/static:ro
     - ./WebAPI/For SSL/cert.crt:/etc/nginx/ssl/cert.crt:ro
     - ./WebAPI/For SSL/private.key:/etc/nginx/ssl/private.key:ro

networks:
  default:
    name: mynet