version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    #ports:
    # - "50352:50352"
    # - "63253:443"
    # - "50354:5001"

  nginx:
    image: nginx
    ports:
     - "80:80"