version: '3.4'

services:
  webapi: &conf
    image: ${DOCKER_REGISTRY-}webapi
    environment: &env
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:441;
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:
     - "441:441"
    volumes:
     - ./IsolatedStorage:/app/IsolatedStorage

  webapi2:
    <<: *conf
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:442;
    ports:
     - "442:442"
    volumes:
     - ./IsolatedStorage:/app/IsolatedStorage:ro

  webapi3:
    <<: *conf
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=https://+:443;
    ports:
     - "443:443"
    volumes:
     - ./IsolatedStorage:/app/IsolatedStorage:ro

  mirror:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: mirror
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:444;
    ports:
     - "444:444"
    build:
      context: .
      dockerfile: WebAPI/Dockerfile

  nginx:
    depends_on:
     - webapi
     - webapi2
     - webapi3
     - mirror
    image: byjg/nginx-extras
    ports:
     - "440:440"
    volumes:
     - ./WebAPI/server/default.conf:/etc/nginx/conf.d/default.conf:ro
     - ./WebAPI/wwwroot:/home/static:ro
     - ./WebAPI/For SSL/cert.pem:/etc/nginx/ssl/cert.pem:ro
     - ./WebAPI/For SSL/private.key:/etc/nginx/ssl/private.key:ro

networks:
  default:
    name: mynet