/*
 * NotStopAlarm
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Logic;

using Microsoft.OpenApi.Models;

using Model;

using Repositories;

using RepositoriesImplementations;

using Serilog;

namespace IO.Swagger
{
	/// <summary>
	/// Startup
	/// </summary>
	public class Startup
	{
		private readonly IWebHostEnvironment _hostingEnv;

		private IConfiguration Configuration { get; }

		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="env"></param>
		/// <param name="configuration"></param>
		public Startup(IWebHostEnvironment env, IConfiguration configuration)
		{
			_hostingEnv = env;
			Configuration = configuration;

			Log.Logger = new LoggerConfiguration()
				.ReadFrom.Configuration(configuration)
				.WriteTo.File("logs/log.txt")
				.CreateLogger();
		}

		/// <summary>
		/// This method gets called by the runtime. Use this method to add services to the container.
		/// </summary>
		/// <param name="services"></param>
		public void ConfigureServices(IServiceCollection services)
		{
			// Add framework services.
			services
				.AddMvc()
				.AddXmlSerializerFormatters();
			services.AddControllers().AddNewtonsoftJson();

			services.AddSingleton<IAlarmClockRepo, AlarmClockFileRepo>();
			services.AddSingleton<INoteRepo, NoteFileRepo>();
			services.AddSingleton(new Stopwatch(
				"Секундомер",
				System.Drawing.Color.White,
				new System.Diagnostics.Stopwatch(),
				new SortedSet<DateTime>(),
				false
			));
			services.AddSingleton<IAlarmClockService, AlarmClockService>();
			services.AddSingleton<INoteService, NoteService>();
			services.AddSingleton<IStopwatchService, StopwatchService>();

			services
				.AddSwaggerGen(c =>
				{
					c.SwaggerDoc("0.1.0", new OpenApiInfo
					{
						Version = "0.1.0",
						Title = "NotStopAlarm",
						Description = "NotStopAlarm (ASP.NET Core 3.1)",
						Contact = new OpenApiContact()
						{
						   Name = "Swagger Codegen Contributors",
						   Url = new Uri("https://github.com/swagger-api/swagger-codegen"),
						   Email = ""
						},
						TermsOfService = new Uri("https://example.com/terms")
					});
					c.CustomSchemaIds(type => type.FullName);
					c.IncludeXmlComments($"{AppContext.BaseDirectory}{Path.DirectorySeparatorChar}{_hostingEnv.ApplicationName}.xml");
					c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());
				});
		}

		/// <summary>
		/// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
		/// </summary>
		/// <param name="app"></param>
		/// <param name="env"></param>
		/// <param name="loggerFactory"></param>
		public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILoggerFactory loggerFactory)
		{
			app.UseRouting();

			//app.UseStaticFiles();
			//app.UseMvc();

			app.UseSwagger(/*c =>
			{
				c.RouteTemplate = "api/v1/swagger-original.json";
			}*/);
			app.UseSwaggerUI(c =>
			{
				//c.RoutePrefix = "api/v1";
				c.SwaggerEndpoint("/swagger/0.1.0/swagger.json", "NotStopAlarm");
			});

			app.UseHttpsRedirection();

			app.UseEndpoints(endpoints =>
			{
				endpoints.MapControllers();
			});

			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
			}
			else
			{
				app.UseExceptionHandler("/Error");

				app.UseHsts();
			}
		}
	}
}
